### ISSUE TITLE
ValueError: Matrix key 'raw.X' already exists!

### ISSUE THREAD

**Issue by slowkow** [lilab-bcb/pegasus#115]
I updated to pegasus 1.0.0

Then I tried to run `pg.log_norm(adata)`, but I get:

```
ValueError: Matrix key 'raw.X' already exists!
```

How is the user supposed to deal with this error?

**Comment by yihming** [comment]
This error happens when users want to rerun `log_norm` after the first running, as the first run already backs up the raw counts.

I've updated `log_norm` for this situation: once seeing `'raw.X'` exist, then use this backup matrix instead of `data.X` for log-normalization.

This will be reflected in our next release.
