### ISSUE TITLE
Question about pc_regress_out

### ISSUE THREAD

**Issue by Zifeng-L** [lilab-bcb/pegasus#133]
Hi, here! 
There were some questions about the function pc_regress_out.
The tutorial showed the returns of this function was stored in data.obsm['X_pca_regressed']. So in the downstream analysis, should I rerun the pca function as follows?
```
pg.identify_robust_genes(data)
pg.calc_signature_score(data, 'cell_cycle_human')
data_cc_genes = data[:, cell_cycle_genes].copy()
pg.pca(data_cc_genes)
data.obsm['X_pca'] = data_cc_genes.obsm['X_pca']
pg.pc_regress_out(data, attrs=['G1/S', 'G2/M','percent_mito','n_genes'])
pg.pca(data, robust=True)
pg.neighbors(data)
pg.louvain(data,resolution=0.6)
pg.umap(data)
```
or just use the data.obsm['X_pca_regressed'] as follows?
```
pg.identify_robust_genes(data)
pg.calc_signature_score(data, 'cell_cycle_human')
data_cc_genes = data[:, cell_cycle_genes].copy()
pg.pca(data_cc_genes)
data.obsm['X_pca'] = data_cc_genes.obsm['X_pca']
pg.pc_regress_out(data, attrs=['G1/S', 'G2/M','percent_mito','n_genes'])
pg.neighbors(data,rep='pca_regressed')
pg.louvain(data,resolution=0.6,rep='pca_regressed')
pg.umap(data,rep='pca_regressed')
```
Because when I run the function of scanpy.pp.regress_out, the output was the updates adata with the corrected data matrix. So I was not sure how to use the output of pegasus function.

**Comment by yihming** [comment]
Hi @Zifeng1995 ,

You should use `data.obsm['X_pca_regressed']` in your downstream analysis. The big difference between Pegasus regress out method and SCANPY is that Pegasus performs this operation on PCs, rather than the count matrix. As a result, in Pegasus, the count matrix would not be corrected, but the PCA result.

Besides, I have some more comments regarding your question:
1. In the tutorial, we calculated PCA from subset of count matrix regarding cell cycle genes only. This is because we want to match the steps of the same tutorial in Seurat and SCANPY, and in this way the regressing out result is more clear. However, in general case, users can determine how to calculate the original PCA themselves based on their situations. And usually one can run `pg.pca` on the count matrix after selecting highly variable features (i.e. after `pg.highly_variable_features` step).
2. In our next release, `pc_regress_out` will be renamed to `regress_out`. And the regressing out tutorial will also be updated accordingly. Just let you know about this change in advance.

**Comment by Zifeng-L** [comment]
> Hi @Zifeng1995 ,
> 
> You should use `data.obsm['X_pca_regressed']` in your downstream analysis. The big difference between Pegasus regress out method and SCANPY is that Pegasus performs this operation on PCs, rather than the count matrix. As a result, in Pegasus, the count matrix would not be corrected, but the PCA result.
> 
> Besides, I have some more comments regarding your question:
> 
> 1. In the tutorial, we calculated PCA from subset of count matrix regarding cell cycle genes only. This is because we want to match the steps of the same tutorial in Seurat and SCANPY, and in this way the regressing out result is more clear. However, in general case, users can determine how to calculate the original PCA themselves based on their situations. And usually one can run `pg.pca` on the count matrix after selecting highly variable features (i.e. after `pg.highly_variable_features` step).
> 2. In our next release, `pc_regress_out` will be renamed to `regress_out`. And the regressing out tutorial will also be updated accordingly. Just let you know about this change in advance.

Thanks for your answers!
