### ISSUE TITLE
pca() got an unexpected keyword argument 'robust'

### ISSUE THREAD

**Issue by Zifeng-L** [lilab-bcb/pegasus#161]
when run pg.pca(TLCL01, robust=True)， something went wrong.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-37fe00e4764c> in <module>()
----> 1 pg.pca(TLCL01, robust=True)

/cluster/home/zfli/anaconda2/envs/peganew/lib/python3.6/site-packages/pegasusio/decorators.py in wrapper_timer(*args, **kwargs)
     10                 def wrapper_timer(*args, **kwargs):
     11                         start = time.perf_counter()
---> 12                         result = func(*args, **kwargs)
     13                         end = time.perf_counter()
     14                         message = f"Function '{func.__name__}' finished in {{:.{precision}f}}s.".format(end - start)

TypeError: pca() got an unexpected keyword argument 'robust'
```
But I have run pg.identify_robust_genes(TLCL01) before. So can anyone help me?

**Comment by yihming** [comment]
Looks like you are using the latest release of Pegasus (v1.3.0) but calling `pg.pca` using the old arguments.

In v1.3.0, we've fixed the reproducibility of PCA step, and therefore no need to keep `robust` parameter. (See https://pegasus.readthedocs.io/en/stable/release_notes.html#version-1-3)

In more details, we have realized past Pegasus versions are not exactly reproducible. For example, if you run Pegasus with multiple threads or on different operating systems, you may get qualitatively equivalent but different results (e.g. different clustering or rotation of UMAP) even with the same data, parameters and random seed. This issue would still happen even if you use docker images. 

Pegasus is not the only tool that suffers this issue. SCANPY also has the same reproducibility issue (see https://github.com/theislab/scanpy/issues/1187 and https://github.com/theislab/single-cell-tutorial/issues/36). We both pinpointed that the issue is caused by sklearn's PCA routine and still did not know how to fix it for a long time. The SCANPY team even recommended to run PCA with a single thread in order to get reproducible outputs (https://github.com/theislab/scanpy/issues/1187). However, this solution is far from ideal --- it does not scale up and also does not work when running on different operating systems.

Fortunately, we have figured out a way of resolving this issue recently. Both SCANPY and Pegasus store the log expression matrix as single-precision floats (float32). When we run PCA on single-precision matrices, the maximum absolute difference of PC coordinates (of all cells) from two consecutive runs can be as high as 0.01, which for sure will change downstream analysis results. However, we found that if we use double-precision floats (float 64) instead, we can reduce the maximum absolute difference to 1e-11. This means that if we convert our matrix to float64 before running PCA and then convert the PC coordinates back to float32, we would have 99.99% of PC coordinates exactly the same and the outliers with a maximum difference ~ 1e-7. 

We have tested this new solution in many scenarios, such as consecutive executions, running with different numbers of threads and running on different operating systems. The new solution works very well and gives almost identical PC coordinates in all tested scenarios.

Hope it helps. And please see https://pegasus.readthedocs.io/en/stable/api/pegasus.pca.html#pegasus.pca for its up-to-date API.

**Comment by Zifeng-L** [comment]
> Looks like you are using the latest release of Pegasus (v1.3.0) but calling `pg.pca` using the old arguments.
> 
> In v1.3.0, we've fixed the reproducibility of PCA step, and therefore no need to keep `robust` parameter. (See https://pegasus.readthedocs.io/en/stable/release_notes.html#version-1-3)
> 
> In more details, we have realized past Pegasus versions are not exactly reproducible. For example, if you run Pegasus with multiple threads or on different operating systems, you may get qualitatively equivalent but different results (e.g. different clustering or rotation of UMAP) even with the same data, parameters and random seed. This issue would still happen even if you use docker images.
> 
> Pegasus is not the only tool that suffers this issue. SCANPY also has the same reproducibility issue (see [theislab/scanpy#1187](https://github.com/theislab/scanpy/issues/1187) and [theislab/single-cell-tutorial#36](https://github.com/theislab/single-cell-tutorial/issues/36)). We both pinpointed that the issue is caused by sklearn's PCA routine and still did not know how to fix it for a long time. The SCANPY team even recommended to run PCA with a single thread in order to get reproducible outputs ([theislab/scanpy#1187](https://github.com/theislab/scanpy/issues/1187)). However, this solution is far from ideal --- it does not scale up and also does not work when running on different operating systems.
> 
> Fortunately, we have figured out a way of resolving this issue recently. Both SCANPY and Pegasus store the log expression matrix as single-precision floats (float32). When we run PCA on single-precision matrices, the maximum absolute difference of PC coordinates (of all cells) from two consecutive runs can be as high as 0.01, which for sure will change downstream analysis results. However, we found that if we use double-precision floats (float 64) instead, we can reduce the maximum absolute difference to 1e-11. This means that if we convert our matrix to float64 before running PCA and then convert the PC coordinates back to float32, we would have 99.99% of PC coordinates exactly the same and the outliers with a maximum difference ~ 1e-7.
> 
> We have tested this new solution in many scenarios, such as consecutive executions, running with different numbers of threads and running on different operating systems. The new solution works very well and gives almost identical PC coordinates in all tested scenarios.
> 
> Hope it helps. And please see https://pegasus.readthedocs.io/en/stable/api/pegasus.pca.html#pegasus.pca for its up-to-date API.

I got it！Thanks！
