### ISSUE TITLE
clustering based on a subset of cells

### ISSUE THREAD

**Issue by hoondy** [lilab-bcb/pegasus#220]
Pegasus's Scrublet implementation works well and we use it to annotate doublets from the single-cell data. However, we would like to **retain doublets** in the data rather than removing them for downstream analysis. We believe there may be false positives and some cells on developmental trajectory do display characteristics of doublets. I wonder if this is possible and what is the best approach to go about this without removing doublet data.

**Comment by bli25** [comment]
Hi @hoondy,

Thanks for your interests in Pegasus!

Of course, please refer to the doublet detection tutorial [here](https://pegasus.readthedocs.io/en/stable/_static/tutorials/doublet_detection.html).

In particular, cell 8 selects only singlets and performs a filtration. If you do not include cell 8, you'll keep everything. The doublet assignment is available at data.obs['demux_type'].

Hope it helps,
Bo

**Comment by hoondy** [comment]
Thanks @bli25 for referring to the tutorial. If you skip cell 8, you retain all the cells and the dim reduction is based on all cells. However, I want to reduce dimension based on *just singlets* and project doublets on the same umap. Is this possible?

**Comment by yihming** [comment]
Hi @hoondy . Unfortunately, we don't provide this feature. For your purpose, you may the tutorial on [transforming new data with UMAP](https://umap-learn.readthedocs.io/en/latest/transform.html) helpful.

In the future, when this machine learning task becomes critical for users, we will definitely consider adding the internal support so that users don't have to do it manually by themselves.
