### ISSUE TITLE
1.2.0 L/S method 

### ISSUE THREAD

**Issue by Dohyun-s** [lilab-bcb/pegasus#253]
Hi, I'm follower and big fan of your work, pegasus.

While following your research paper "Cumulus provides cloud-based data analysis for large-scale single-cell and single-nucleus RNA-seq",  I could not find L/S method in your newest version. Then I look at other versions of your code and found L/s method is deleted and obsolete after 1.2.0 version.

May I ask you reason why L/S method is not recommended as batch correction method?
Thank you very much.

**Comment by bli25** [comment]
Hi @Dohyun-s ,

Thanks for your interests in Pegasus!

We retired L/S method because Harmony (we have Harmony-PyTorch implementation) is a better alternative. One big con of L/S method is that it cannot handle datasets with different proportion of cell types (e.g. one sample has 70% immune cells and 30% fibroblast, while the other sample has 50%/50%). 

The other reason is that L/S method is not well modularized. It couples with Pegasus by requiring some pre-processing/post-processing code. 

We plan to add a Python implementation of ComBat to later versions of Pegasus, which can be used as a slower version of the L/S method, but well modularized.

Hope it helps,
Bo
