### ISSUE TITLE
using cellbender outputs

### ISSUE THREAD

**Issue by jackhump** [lilab-bcb/pegasus#299]
Hi all, we're really enjoying using Pegasus for our single-nucleus RNA-seq work, it's a fantastic software toolkit.

Recently, we've been using cellbender to remove ambient RNAs. Do you have advice on how best to use the corrected counts from the _filtered.h5 files that cellbender outputs when aggregating samples with Pegasus? 

As far as I can see it's using the original counts, as the total counts per cell and genes per cell do not differ between Pegasus runs using the raw (x-axis) and filtered (y-axis) h5 objects:

![image](https://github.com/lilab-bcb/pegasus/assets/11192505/6ff7470f-bf0d-4ed3-af8e-dfd5ee1d7e42)

**Comment by jackhump** [comment]
closed because I didn't read the cellbender documentation properly - both H5 files produced by pegasus contain the background-removed counts, the filtered.h5 just removes the barcodes belonging to empty droplets. 
Sorry.

**Comment by yihming** [comment]
Hi @jackhump ,

Sorry for my late response. Yes, you are correct about the 2 h5 files generated by cellbender. And when you use pegasus to aggregate multiple h5 files, unless you specify parameters like `min_genes`, `max_genes`, etc. (see https://pegasus.readthedocs.io/en/stable/api/pegasus.aggregate_matrices.html), otherwise the process doesn't remove cells or genes in the original files.

Feel free to reach out to us for any question in the future.


Sincerely,
Yiming
