### ISSUE TITLE
pegasus demuxEM

### ISSUE THREAD

**Issue by bio-la** [lilab-bcb/pegasus#33]
Hi,
thanks for putting together all these functionalities in one tool!

i'm trying to demultiplex my nuclei-hashed data with demuxEM, and I get A LOT of unknown (50% of data). I was hoping you could clarify on what exactly determines that a cell is unknown, the only mention i found is this: 
--min-signal-hashtag <count> 
Any cell/nucleus with less than <count> hashtags from the signal will be marked as unknown. [default: 10.0]

The cells deemed unknown have way above 10 UMI for the hashtag library when I check the raw data. The distribution of hashtags UMI is clearly bimodal for background and signal, but the one deemed background is practically overlapping the signal one and the difference between their mean is less than one order of magnitude(signal is higher than 10^3 and background is above 10^2), so I wonder if there's a better selection of params I'd better use, I was just testing default params.

also, if what comes out of the cellranger pipeline are CELLS (above n UMI threshold) and GEMS, the tool is demultiplexing a lot of GEMS, nothing wrong with that, but it makes a bit complicated to get out the right percentage of cells demultiplexed. 

hope you can clarify how to better run the demultiplexing and interpret the results! 
thanks for your help!

**Comment by bli25** [comment]
Hi @bio-la ,

Thanks a lot for interest in using Pegasus. 

Sure. DemuxEM first try to remove ambient HTOs by matching the distribution learned in the empty droplets. After removing the ambients, if the total number of hashtags (signal) are < 10.0, DemuxEM will assign 'unknown' to this GEM. Please refer to our paper, https://www.nature.com/articles/s41467-019-10756-2, for more details.

For your second question, you can adjust the --min-num-genes <number> and --min-num-umis <number>  options to be more stringent. Since in the cluster subcommand we have another round of QC control, for DemuxEM we set the thresholds loose.

Hope it helps,
Bo
